version: '2'
services:
  grafana:
    image: grafana/grafana:9.3.1
    ports:
      - 3000:3000
    volumes:
      - grafana_plugins:/var/lib/grafana/plugins
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    networks:
      - elastic
    ports:
      - 5601:5601
    

  
volumes:
  grafana_plugins:
networks:
  elastic: